spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://mysql:3306/pos
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expirationTime: 60

app-setup:
  alreadySetup: false
  adminUsername: admin
  adminPassword: admin
  adminEmail: example@gmail.com

app:
  base:
    url: http://localhost:8080
    attachment-endpoint: /api/v1/attachments

web:
  cors:
    allowed-origins: "http://localhost:3015"
