spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret:
  expirationTime: 60
app-setup:
  alreadySetup: false
  adminUsername: admin
  adminPassword: admin
  adminEmail: example@gmail.com