name: Java CI with Maven and Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

      # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

      # Cài đặt Maven dependencies và build ứng dụng
    - name: Build with Maven
      run: mvn clean install -DskipTests

      # Thiết lập SSH key cho kết nối với máy chủ
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}  # SSH private key từ GitHub Secrets

      # Triển khai ứng dụng lên máy chủ
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'bash /path/to/deploy_script.sh'
