name: Java CI with Maven and Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4. Set up SSH key for connecting to the server
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # 5. Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            PROJECT_DIR="/home/user/my-app"
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            # Kiểm tra nếu thư mục chưa có mã nguồn
            if [ ! -d ".git" ]; then
              git clone git@github.com:vktrung/LakluRestaurantManagement.git  .
            fi

            git pull origin master

            # Chạy ứng dụng từ file JAR trong thư mục target
            java -jar target/pos-0.0.1-SNAPSHOT.jar
          EOF
